s3:
  access-key: ${ACCESS_KEY}
  secret-key: ${SECRET_KEY}
  bucket-name: ${BUCKET_NAME}
  region: ${REGION}


cloud:
  aws:
    credentials:
      accessKey: ${ACCESS_KEY}
      secretKey: ${SECRET_KEY}
    region:
      static: ${REGION}
    stack:
      auto: false


spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
